# Generated by Django 5.0 on 2023-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(default='Null', upload_to='media/%Y/%m/%d'),
        ),
    ]
